# Generated by Django 3.2.9 on 2021-11-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211122_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/blog/%Y/%m/%d', verbose_name='Фотография котика'),
        ),
    ]
